[package]
name                   = "cargo-smysl-evidence"
description            = "cargo-smysl: evidence stage"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
authors.workspace      = true
repository.workspace   = true

[dependencies]
cargo-smysl-corpus = { workspace = true }
cargo-smysl-facts  = { workspace = true }
smysl              = { workspace = true }
serde              = { workspace = true }
thiserror          = { workspace = true }

[dev-dependencies]
serde_json         = { workspace = true }
